### ISSUE TITLE
Support for handling invalid characters

### ISSUE THREAD

**Issue by uBadRequest** [lc/gau#1]
Hello!

Awesome tool, much faster than my bash script... but it appears to have an issue with invalid characters

2020/03/15 01:35:37 Could not decode json: invalid character '<' looking for beginning of value

This is separate issue, but entire script stops when a timeout occurs... specifically seeing it with alienvault.

Thanks!

**Comment by lc** [comment]
Thanks for bringing this to my attention, this shouldn't have been happening! Fixed that now.

**Comment by SimoneBovi** [comment]
Hi!
Just updated to the new version but I am still seeing the same exact behavior :(
