### ISSUE TITLE
Exclude unwanted files urls.

### ISSUE THREAD

**Issue by KathanP19** [lc/gau#10]
It would be great if you can add --exclude function to gau so that we can exclude unwanted files url.
Thank you

**Comment by lc** [comment]
Hey @KathanP19, 

Would this be to exclude certain file extensions like this? Say you didn't want `.gif` files:

`--exclude gif`

**Comment by KathanP19** [comment]
yes exactly , cause file is getting very large as more and urls are fetched which are unwanted.

**Comment by cihanmehmet** [comment]
you can use grep for unwanted file extensions.

```shell
gau webscantest.com | grep -vE ".(jpg|jpeg|gif|css|tif|tiff|png|ttf|woff|woff2|ico|pdf|svg|txt|js)"
```
```powershell
echo "webscantest.com" | grep -vE ".(jpg|jpeg|gif|css|tif|tiff|png|ttf|woff|woff2|ico|pdf|svg|txt|js)"
```

**Comment by KathanP19** [comment]
> you can use grep for unwanted file extensions.
> 
> ```shell
> gau webscantest.com | grep -vE ".(jpg|jpeg|gif|css|tif|tiff|png|ttf|woff|woff2|ico|pdf|svg|txt|js)"
> ```
> 
> ```powershell
> echo "webscantest.com" | grep -vE ".(jpg|jpeg|gif|css|tif|tiff|png|ttf|woff|woff2|ico|pdf|svg|txt|js)"
> ```

ya that can be one solution but gau itself doesn't fetch url , that can save some time & data.

**Comment by lc** [comment]
@KathanP19, gau itself doesn't actually fetch any of these URLs, it only fetches the sources (Wayback, AlienVault, CommonCrawl)

**Comment by lc** [comment]
Since gau does not do any fetching of the result URLs, I'm going to close this, one can use `rg` or `grep`. If I add functionality to fetch the URLs, I'll make sure to keep this issue in mind. 

Thanks!
