### ISSUE TITLE
gau-2.1.2 binary wont run if outside of a github repository

### ISSUE THREAD

**Issue by TH3-F001** [lc/gau#103]
When following the installation instructions in the readme; moving the binary to a location external to the github repository results in the following error:

```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

Moving the binary back to the original git folder however works fine.

...Maybe I've just never gone deep enough with git, or this is a go thing, or im just more of a noob than I thought, but I've never seen this kind of error before.

**Comment by lc** [comment]
you're probably running `gau` in a folder that has a subdirectory called "gau"
