### ISSUE TITLE
can't install gau

### ISSUE THREAD

**Issue by FreakyCarlos** [lc/gau#105]
collect2: error: ld returned 1 exit status
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'gau-2.1.2-1': 
error: packages failed to build: gau-2.1.2-1

**Comment by Prathameshbhujbal** [comment]
- Same here. Not able to install gau. 
- Error displayed: 
# github.com/deckarep/golang-set/v2
/root/go/pkg/mod/github.com/deckarep/golang-set/v2@v2.3.0/iterator.go:30:17: error: expected ‘]’
   30 | type Iterator[T comparable] struct {
      |                 ^
/root/go/pkg/mod/github.com/deckarep/golang-set/v2@v2.3.0/iterator.go:32:9: error: expected declaration
   32 |         stop chan struct{}
      |         ^
/root/go/pkg/mod/github.com/deckarep/golang-set/v2@v2.3.0/iterator.go:33:1: error: expected declaration
   33 | }
      | ^
/root/go/pkg/mod/github.com/deckarep/golang-set/v2@v2.3.0/iterator.go:36:18: error: expected ‘)’
   36 | func (i *Iterator[T]) Stop() {
      |                  ^
...... (error message was very long around 500 lines)

- I have tried installing gau from source, from github, from binary, from docker but none of them is working

**Comment by bigmo6286** [comment]
also having the same issues here

**Comment by lc** [comment]
Please update your golang version
