### ISSUE TITLE
".gau.toml" doesn't work

### ISSUE THREAD

**Issue by 0xspade** [lc/gau#110]
I already blacklist the extension "jpg" and, "png" in the .toml file and after I scan my target again, there are still results of "jpg" and, "png".

**Comment by 0xspade** [comment]
In addition, I dont see that gau is using the apikey I provided.

**Comment by Moskitoz** [comment]
the tool not working after installing it with this cmd

go install github.com/lc/gau/v2/cmd/gau@latest

WARN[0000] error reading config: open /home/**duraid**/.gau.toml: no such file or directory

**Comment by Disarm3** [comment]
how did you resolve this? Im with the same issue

**Comment by math-ematics** [comment]
Fix this crap

**Comment by thezakman** [comment]
Just add the missing file in the PATH that is needed, with the default settings:
https://github.com/lc/gau/raw/master/.gau.toml

```threads = 2
verbose = false
retries = 15
subdomains = false
parameters = false
providers = ["wayback","commoncrawl","otx","urlscan"]
blacklist = ["ttf","woff","svg","png","jpg"]
json = false

[urlscan]
  apikey = ""

[filters]
  from = ""
  to = ""
  matchstatuscodes = []
  matchmimetypes = []
  filterstatuscodes = []
  filtermimetypes = ["image/png", "image/jpg", "image/svg+xml"]```

**Comment by b-hermes** [comment]
After adding the file now I got this error each time I try to run:

WARN[0000] error reading config: While parsing config: (18, 64): parsing error: no value can start with `

**Comment by deljilal** [comment]
gau     
WARN[0000] error reading config: open /home/zabiiiiii/.gau.toml: no such file or directory 

any fix

**Comment by nadir-sh** [comment]
WARN[0000] error reading config: Config file /home/nadir/.gau.toml not found, using default config  
i have this error could anyone fix this ?

**Comment by mcamou** [comment]
Do you have a .gau.toml file? If not, the message is simply telling you that it will use the default configuration. I cannot fix this, if you're fine with the default configuration just disregard it, otherwise create an appropriate .gau.toml file according to the docs.

**Comment by himanshubomble17** [comment]
Remove your existing Gau 
Refer to this, worked for me! 
https://iha089.org/mastering-gau-how-to-install-and-utilize/
