### ISSUE TITLE
GAU .toml not working

### ISSUE THREAD

**Issue by Disarm3** [lc/gau#117]
This error prevents me from executing GAU correctly:

WARN[0000] error reading config: open /home/kali/.gau.toml: no such file or directory

**Comment by thezakman** [comment]
Just add the missing file in the PATH that is needed, with the default settings:
https://github.com/lc/gau/raw/master/.gau.toml

```threads = 2
verbose = false
retries = 15
subdomains = false
parameters = false
providers = ["wayback","commoncrawl","otx","urlscan"]
blacklist = ["ttf","woff","svg","png","jpg"]
json = false

[urlscan]
  apikey = ""

[filters]
  from = ""
  to = ""
  matchstatuscodes = []
  matchmimetypes = []
  filterstatuscodes = []
  filtermimetypes = ["image/png", "image/jpg", "image/svg+xml"]```

**Comment by Disarm3** [comment]
I created the file .gau.toml on the path mentioned (/home/kali/)  with the following code:

`threads = 2
verbose = false
retries = 15
subdomains = false
parameters = false
providers = ["wayback","commoncrawl","otx","urlscan"]
blacklist = ["ttf","woff","svg","png","jpg"]
json = false

[urlscan]
  apikey = ""

[filters]
  from = ""
  to = ""
  matchstatuscodes = []
  matchmimetypes = []
  filterstatuscodes = []
  filtermimetypes = ["image/png", "image/jpg", "image/svg+xml"]`

I tested GAU using a .txt file with a random domain but it doesn't return any output. The command I used:

`cat test.txt | ./gau`

**Comment by thezakman** [comment]
Not returning nothing dosen't mean that is broken.

Try on a famous domain, If It works It means that the one from your TXT
file have never been indexed. And the error was fixed, right?

Em sáb., 18 de nov. de 2023 10:37, Disarm3 ***@***.***>
escreveu:

**Comment by Disarm3** [comment]
I tested it on amazon.com using a .txt file but again it didn't show any output. When i ran it outside a .txt file it worked normally ($ ./gau amazon.com). Is there a way i can fix this?

**Comment by sudo-awk** [comment]
same here

**Comment by mcamou** [comment]
See #133
