### ISSUE TITLE
How does one pronounce the name of your tool? [URGENT]

### ISSUE THREAD

**Issue by EdOverflow** [lc/gau#12]

**Comment by karelorigin** [comment]
It's pronounced as "gau" not "gau"

**Comment by jimen0** [comment]
I confirm I was able to reproduce the issue locally.

**Comment by lc** [comment]
Hello, this is definitely an issue, it's pronounced "g-ow", Stok says it right here:

https://youtu.be/NugCDCumPxs?t=140

Closing as fixed now
