### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by kali787** [lc/gau#123]
Everytime I hit enter to launch the attack it doesnt work also tried to update it and nothing plus tried git clone and not working any siggestions?

**Comment by ved009** [comment]
Same here. I did a downgrade to a previous version and it is working now.

**Comment by kali787** [comment]
Ook thanks!!!

**Comment by lc** [comment]
My best guess is that you have an invalid toml file at: `$HOME/.gau.toml`

https://github.com/lc/gau/blob/master/.gau.toml
