### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by badhacker0x1** [lc/gau#126]
When I try to run gau. Im facing this issue. 

fatal: not a git repository (or any of the parent directories): .git

**Comment by badhacker0x1** [comment]
solved

**Comment by logans3c** [comment]
> solved

how did you solve it ?

**Comment by saymenn** [comment]
@logans3c u can either compile the binary urself instead as suggested by corben in another closed issue, or what worked for me was to use the abs path at /root/go/bin/gau

**Comment by badhacker0x1** [comment]
@logans3c I was using zsh. There is a utility called gau in zsh so it was not working.
