### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by xtermed** [lc/gau#129]
seems gau has broken. haven't looked into why because im worthless though

**Comment by b-hermes** [comment]
it's the ".gau.toml" error message?

**Comment by MrLups** [comment]
it's 100% broken

**Comment by lc** [comment]
It work's fine on my end. Please give your golang version and show your version of gau:

```
gau --version
```

**Comment by lc** [comment]
My best guess is that you have an invalid toml file at: `$HOME/.gau.toml`

https://github.com/lc/gau/blob/master/.gau.toml
