### ISSUE TITLE
gau not showing urls correctly

### ISSUE THREAD

**Issue by prasgop** [lc/gau#130]
When I try gau, it's either gives no results or showing something like the below output. I have checked with facebook,com and it's no different. Result pretty much remains the same no matter I use google.com or https://google.com/. I am not seeing any other paths beyond that.
![gau](https://github.com/lc/gau/assets/116869728/b28ac0a3-71b1-4f17-8162-1374771b6552)

**Comment by lc** [comment]
Usage is `gau <domain>`, no scheme or `/` should be in the search request.

It may have to do with these sites `/robots.txt`, but it works fine on most sites.

Ex: `gau reddit.com`

**Comment by prasgop** [comment]
I am not seeing any difference in the output. Please find attached below. That error in beginning was showing up before too until and I copied .gau.toml to $HOME/ and showing up again after removing it. The results below remain the same regardless. Am I doing it wrong?
![gau](https://github.com/lc/gau/assets/116869728/4e0685a8-6a10-42e5-9081-f14ab4ea6332)

**Comment by prasgop** [comment]
gau google.com is working now after showing significantly multiple rows of https://www.google.com/ and http://www.google.com/ but cat domains.txt | gau is still showing like the below. Am I doing something wrong? How can I use it in pipe?
![gau](https://github.com/lc/gau/assets/116869728/dfce939f-a21c-4658-b4e7-5d036c364114)
 
![gau2](https://github.com/lc/gau/assets/116869728/adfb7a08-9bc9-44a2-830e-44111973699c)
![gau3](https://github.com/lc/gau/assets/116869728/57986c68-d5c5-4278-82a2-bda2e0f7afd7)
