### ISSUE TITLE
error reading config: open /home/g0xkayala/.gau.toml: no such file or directory

### ISSUE THREAD

**Issue by 0xKayala** [lc/gau#133]
error reading config: open /home/g0xkayala/.gau.toml: no such file or directory

![image](https://github.com/lc/gau/assets/16838353/36c153ed-26f5-49b3-8fc2-089f6d8f7be9)

**Comment by fantomcheg** [comment]
The same

**Comment by tyloren0a** [comment]
same

**Comment by tyloren0a** [comment]
@lc

**Comment by 0xab01** [comment]
Simple create a .gau.toml file in your home directory and put this code 

threads = 2
verbose = false
retries = 15
subdomains = false
parameters = false
providers = ["wayback","commoncrawl","otx","urlscan"]
blacklist = ["ttf","woff","svg","png","jpg"]
json = false

[urlscan]
  apikey = ""

[filters]
  from = ""
  to = ""
  matchstatuscodes = []
  matchmimetypes = []
  filterstatuscodes = []
  filtermimetypes = ["image/png", "image/jpg", "image/svg+xml"]

 and then save then run the code your problem will be solved

**Comment by adibabdala123** [comment]
you save me mate! thx forever

**Comment by ciznaa** [comment]
same, anyone have a fix?

**Comment by achufistov** [comment]
just create a config file based on the sample and the error will disappear 
https://github.com/lc/gau/blob/master/.gau.toml

**Comment by siddiqodiq** [comment]
thanks bro, its workin on me

> just create a config file based on the sample and the error will disappear https://github.com/lc/gau/blob/master/.gau.toml

**Comment by mcamou** [comment]
@lc if you like I could fix it so that if the configuration does not exist it uses the default, WDYT?

**Comment by lc** [comment]
Hey @mcamou, yeah I should’ve implemented this awhile ago - tons of these issues get opened when there’s an easy fix. If you’re bored feel free, otherwise I can add it to my todo list :)

**Comment by mcamou** [comment]
I'll go ahead and do it. I'm doing Hacktoberfest, not sure if something this simple will count but couldn't hurt.

**Comment by mcamou** [comment]
@lc PR here: https://github.com/lc/gau/pull/151

**Comment by jagat-singh-chaudhary** [comment]
![Image](https://github.com/user-attachments/assets/3ac6dc16-5fa3-4cb1-8f68-bbdf2ec69a93)

**Comment by jagat-singh-chaudhary** [comment]
![Image](https://github.com/user-attachments/assets/3d405505-a855-47e9-bec5-fb2a7c3085b0)

**Comment by himanshubomble17** [comment]
Remove your existing Gau 
Refer to this, worked for me! 
https://iha089.org/mastering-gau-how-to-install-and-utilize/

**Comment by baase666** [comment]
nah fam~ ain't gettin fooled~~~
