### ISSUE TITLE
WARN[0009] http://url2547.tesla.com - failed to fetch wayback pagination: API responded with non-200 status code  provider=wayback

### ISSUE THREAD

**Issue by a6thmfsin** [lc/gau#135]
Hey is anyone else having this error? I have had it for probably 3 days now and have no idea why (im not using Docker)?
command:
cat ~/Desktop/reconfw/domain-files/live_domains.txt | gau --verbose > ~/Desktop/reconfw/endpoints/gau-endpoints.txt
stdout output:
WARN[0003] https://powerhub.energy.tesla.com - failed to fetch wayback pagination: dial tcp4 207.241.237.3:443: connect: connection refused  provider=wayback
WARN[0003] http://akamai-apigateway-stg-materials.tesla.com - failed to fetch wayback pagination: dial tcp4 207.241.237.3:443: connect: connection refused  provider=wayback
WARN[0003] http://simpleorigin.tesla.com - failed to fetch wayback pagination: dial tcp4 207.241.237.3:443: connect: connection 
.............etc

curl --verbose 207.241.237.3:443:
*   Trying 207.241.237.3:443...
* connect to 207.241.237.3 port 443 from 192.168.1.149 port 48702 failed: Connection refused
* Failed to connect to 207.241.237.3 port 443 after 178 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to 207.241.237.3 port 443 after 178 ms: Couldn't connect to server

Tried to remove wayback from .gau.toml file and same output:
INFO[0010] no results for https://akamai-apigateway-packaging2.tesla.com  provider=commoncrawl
WARN[0010] http://autodiscover.tesla.com - API responded with non-200 status code  provider=commoncrawl
WARN[0010] https://akamai-apigateway-stg-materials.tesla.com - API responded with non-200 status code  provider=commoncrawl
.............etc

I have tried with and without a VPN aswell as proxy w changed DNS servers and im not rate limited from https://wayback-api.archive.org/, API works https://archive.org/wayback/available?url=tesla.com, normal website works http://web.archive.org/web/20240510191323/https://www.tesla.com/ etc and as both providers same output idk.. Anyone have any ideas?? does the python httpx have anything to do with it couse i deleted httpx from my pc someday ago (have reinstalled w pip) ago and not sure if thats why it broke. Ive tried reinstalling gau and using ~/go/bin/gau but still wont work. Please someone help.

-0xgreyhound

**Comment by microphone-mathematics** [comment]
hey @a6thmfsin ,
I'm getting the same issue.
If you run gau through a proxy you will notice that even though the archive.org api works, the first request that gau does to get the number of pages fails with a 400 error.

It seems that wayback API changed something and now gau is broken.

I played a bit with the code, and adding &pageSize=1 GET parameter to the pagination request while also changing fl=original to fl=numpages seem to make the request return the correct number of pages.
But some more changes might be needed to be able to parse the new request.

**Comment by lc** [comment]
Fixed in v2.2.2 release!

**Comment by row248-hola** [comment]
@lc 
There is one VirusTotal detection for the latest v2.2.3 
https://www.virustotal.com/gui/file/9cc2db8e661eb569f0deb23ad4b210a9ddd0df3d03767c5978656851a4e00c27/detection

**Comment by a6thmfsin** [comment]
+1 @lc

**Comment by lc** [comment]
Hey all,

Can you check your gau version?

```
$ gau --version

gau version: 2.2.3
```

**Comment by a6thmfsin** [comment]
+1 @lc

> Hey all,
> 
> Can you check your gau version?
> 
> ```
> $ gau --version
> 
> gau version: 2.2.3
> ```
> 
> cc: @a6thmfsin

Now everything seems to work here is verbose output, only did a quick test on my windows laptop with wsl2:
.......
https://cs.money/csgo/karambit-marble-fade-factory-new/35386439013/
https://cs.money/csgo/karambit-marble-fade-factory-new/35466828937/
https://cs.money/csgo/karambit-marble-fade-factory-new/35473218349/
https://cs.money/csgo/karambit-marble-fade-factory-new/35509686457/
https://cs.money/csgo/karambit-marble-fade-factory-new/35558805228/
https://cs.money/csgo/karambit-marble-fade-factory-new/35579957901/
https://cs.money/csgo/karambit-marble-fade-factory-new/35622381842/
https://cs.money/csgo/karambit-marble-fade-factory-new/35689425908/
https://cs.money/csgo/karambit-marble-fade-factory-new/35707138102/
https://cs.money/csgo/karambit-marble-fade-factory-new/35918263207/
https://cs.money/csgo/karambit-marble-fade-factory-new/35938976341/
https://cs.money/csgo/karambit-marble-fade-factory-new/36088421560/
https://cs.money/csgo/karambit-rust-coat-battle-scarred
https://cs.money/csgo/karambit-rust-coat-battle-scarred/36998583152/
^C
greyhound@LAPTOP-xxx:~$ cat tmp.txt | gau --verbose > tmp2.txt
WARN[0000] error reading config: open /home/greyhound/.gau.toml: no such file or directory
INFO[0000] fetching cs.money                             page=0 provider=wayback
INFO[0010] fetching cs.money                             page=1 provider=wayback
INFO[0012] fetching cs.money                             page=0 provider=commoncrawl
INFO[0013] fetching cs.money                             page=0 provider=otx
INFO[0013] fetching cs.money                             page=1 provider=otx
INFO[0013] fetching cs.money                             page=2 provider=otx
INFO[0014] fetching cs.money                             page=3 provider=otx
INFO[0014] fetching cs.money                             page=0 provider=urlscan
INFO[0014] fetching cs.money                             page=1 provider=urlscan
WARN[0014] cs.money - failed to fetch urlscan: API responded with 400 status code  provider=urlscan
INFO[0014] fetching paypal.com                           page=0 provider=wayback
^C
greyhound@LAPTOP-xxx:~$

------------------

greyhound@LAPTOP-xxx:~$ wc -l tmp2.txt
73317 tmp2.txt
greyhound@LAPTOP-xxx:~$ cat tmp2.txt | grep ? | head -n 10
https://cs.money/1.0/auction/lots?appId=570&limit=200&offset=0&order=desc&sort=betsAmount&status=running
https://cs.money/1.0/auction/lots?appId=730&limit=200&offset=0&order=desc&sort=betsAmount&status=running
https://cs.money/1.0/auction/my-lots?appId=570&limit=200&offset=0&order=desc&sort=betsAmount&status=running
https://cs.money/1.0/auction/my-lots?appId=730&limit=200&offset=0&order=desc&sort=betsAmount&status=running
https://cs.money/1.0/market/history?limit=30&noCache=true
https://cs.money/1.0/market/notifications?updatedFrom=1667741008998&limit=60
https://cs.money/1.0/market/notifications?updatedFrom=1667959278785&limit=60
https://cs.money/1.0/market/notifications?updatedFrom=1668558285858&limit=60
https://cs.money/1.0/market/notifications?updatedFrom=1668558294841&limit=60
https://cs.money/1.0/market/notifications?updatedFrom=1668558304803&limit=60
greyhound@LAPTOP-xxx:~$

Only thing i saw was "WARN[0014] cs.money - failed to fetch urlscan: API responded with 400 status code  provider=urlscan" but i believe thats probably only some retry?

- greyhound
