### ISSUE TITLE
Flag to set custom location of config file

### ISSUE THREAD

**Issue by MillerMedia** [lc/gau#146]
I think it would great to have a --config flag (or something similar) to point to a custom location for the toml file rather than always have it look for the file in the user's home folder.

I am using gau in an automation script I'm building for bug bounty hunting and would be great to be able to move the compiled automation to different machines with this binary included in the package. Because of this, I would have to manually create a gau.toml on all machines I use it on.

**Comment by MillerMedia** [comment]
Just submitted a PR for this here:
https://github.com/lc/gau/pull/147

**Comment by lc** [comment]
https://github.com/lc/gau/releases/tag/v2.2.4
