### ISSUE TITLE
 gau version: 2.2.4  ----still error WARN[0000] error

### ISSUE THREAD

**Issue by uskolor** [lc/gau#153]
HI Team 

I still have this issue

1. go install github.com/lc/gau/v2/cmd/gau@latest
2. gau --version   gau version: 2.2.4
3. printf example.com | gau

WARN[0000] error reading config: Config file /home/john/.gau.toml not found, using default config

**Comment by lc** [comment]
Either create the configuration there or ignore. It's not a fatal error
