### ISSUE TITLE
I downloaded gau but I am not able to run

### ISSUE THREAD

**Issue by r-arpeet82** [lc/gau#16]
I have downloaded gau, with the  command specified in the installation GO111MODULE=on go get -u -v github.com/lc/gau . But I am not able to locate where is my gau saved. As I downloaded it in Desktop once, once in home. Tried to run from both locations but it says gau: No such file or directory. And on giving command like ./gau it says ./gau: No such file or directory. Any solution please.

**Comment by skynet594** [comment]
Use the second option by downloading the binary file..I'm including the link below.
https://github.com/lc/gau/releases/download/v1.0.2/gau_1.0.2_linux_amd64.tar.gz.
Change the directory to where the downloaded file is saved and use the following commands below
tar xvf gau_1.0.2_linux_amd64.tar.gz
mv gau /usr/bin/gau

I hope this helps.
Anyways which OS are you using??

**Comment by r-arpeet82** [comment]
Thank you that worked.
