### ISSUE TITLE
Output to JSON file - feature request

### ISSUE THREAD

**Issue by w9w** [lc/gau#17]
Hey Corben! I'd like to request a new feature - stdout to JSON file to a specific directory. I need it for another script and I can use other methods to convert the output to JSON but it'd cool if you add it to your tool straightaway.

Thanks and have a nice day. Max (@w2w).

**Comment by lc** [comment]
Hey @w9w,

Good idea, I've been meaning to add output functionality, so I've just done that. There's now a `-o` flag to specify a file to output results to, as well as a `-json` flag to specify JSON output.

Here's the release: https://github.com/lc/gau/releases/tag/v1.0.3
