### ISSUE TITLE
[BUG] GAU is breaking certain times 

### ISSUE THREAD

**Issue by virenpawar** [lc/gau#19]
First of all thanks for creating this awesome tool, it helps greatly in daily usage to find multiple vulnerabilities. Coming to the point, `gau` breaks certain times, there are multiple cases I guess, and not all times these cases appears to be faulty:
1. When response contains `?` mark sign.
2. When response length is long.

I have two sites which demonstrate this, but I don't want to mark them here, to know this one I can mail you if you wish or I can DM you, as you prefer. One more thing I have compared results with `waybackurls` and found that it is providing the appropriate results in format.

**Comment by lc** [comment]
Hi @virenpawar,

Thanks for opening up this issue. If you could email me these two sites to demonstrate this I would appreciate it! You can contact me at corben[at]threat.dev.

**Comment by lc** [comment]
Hi @virenpawar,

Thanks for bringing this to my attention, I just fixed this issue and published a new release. Thanks!
