### ISSUE TITLE
Support for handling invalid characters with AlientVault

### ISSUE THREAD

**Issue by SimoneBovi** [lc/gau#2]
Hi,
unfortunately I am seeing the same exact behaviour described here (https://github.com/lc/gau/issues/1) also after updating to the new version.

Feel free to DM on Twitter and I will give you the exact URL I am trying.

Thanks a lot, your tool is great!

**Comment by lc** [comment]
Thanks! I had forgotten to remove one last `log.Fatal`, this is fixed now.
