### ISSUE TITLE
gau output (-o) option is not working

### ISSUE THREAD

**Issue by sofily-security** [lc/gau#20]
I tired the below. The output is showing on the console but it's not really creating and dumping into the file.
root@kali:~# gau --version
gau version: 1.0.3
root@kali:~#
root@kali:~# gau target.com -subs -o target.txt
root@kali:~# ls -l
total 0
root@kali:~#

**Comment by lc** [comment]
Hi @sofily-security,

Thanks for opening this issue. What happens when you run this?

`gau -subs -o target.txt target.com`

**Comment by sofily-security** [comment]
Hello Ic,

Now when I run with your provided syntax, it's working. It prints the output on console + creating and dumping the result into a file.
root@kali:~# **gau -subs -o target.txt target.com**
root@kali:~# ls -l target.txt
-rw-r--r-- 1 root root 593920 Sep  3 20:39 framer.txt
root@kali:~#

But again, just to test the previous case, I again run with the initial syntax. It ONLY prints the output on console BUT NOT creating and dumping the result into a file.
root@kali:~# **gau target.com -subs -o target_2.txt**
root@kali:# ls -l target_2.txt
ls: cannot access 'target_2.txt': No such file or directory
root@kali:~#


Now this leads me to ask one question:
Why the tool acts differently when providing the in the middle of the command or at the last of the command?

**Comment by lc** [comment]
@sofily-security this acts differently because of Golang's flag package and my use of NArg

https://github.com/lc/gau/blob/master/main.go#L102
```
	if flag.NArg() > 0 {
		domains = flag.Args()
	}
```

NArg is the number of arguments remaining after flags have been processed.

**Comment by sofily-security** [comment]
Understood. Thanks for your prompt response. Good learning tips for me 👍

**Comment by lc** [comment]
I'm going to look into this more and see if I can find a solution, so I'll leave this open for now. Thanks!

**Comment by BastienFaure** [comment]
I have another behavior might be tied to this issue. When I specify an output file with `-o`, nothing is printed on the console. I that by design or just a miss ?

Thanks !

**Comment by lc** [comment]
@BastienFaure that is by design

**Comment by lc** [comment]
Hey @sofily-security this is now fixed in the new version of gau!
