### ISSUE TITLE
gau: command not found

### ISSUE THREAD

**Issue by kabeersaxena** [lc/gau#21]
I Tried it by clone , gau_1.0.3_linux_amd64.tar.gz (extraction) , and by using go.

but when i try gau -h it shows 
gau: command not found

root@kali:~# export PATH=$PATH:/usr/local/go/bin
root@kali:~# go get -u -v github.com/lc/gau
github.com/lc/gau (download)
github.com/json-iterator/go (download)
github.com/modern-go/concurrent (download)
github.com/modern-go/reflect2 (download)
root@kali:~# gau -h
bash: gau: command not found

**Comment by kabeersaxena** [comment]
i got it solved by. deleting their path and re extracting them again :)

**Comment by vansh1** [comment]
> i got it solved by. deleting their path and re extracting them again :)

can you tell how
