### ISSUE TITLE
fatal: pathspec 'domain.com' did not match any files

### ISSUE THREAD

**Issue by Linuxinet** [lc/gau#26]
When I try to use this tool
It showing error like this
![IMG_20201104_154644](https://user-images.githubusercontent.com/55936553/98098951-fc410c00-1eb4-11eb-9fc4-d91afe41cd6a.jpg)

`fatal: pathspec 'video.uber.com' did not match any files`

**Comment by famdude** [comment]
How is it closed, while there is no solution for it?
I have the same issue. Any solution?
