### ISSUE TITLE
Add Blacklist Option

### ISSUE THREAD

**Issue by m0chan** [lc/gau#29]
You should add a `-b` flag to blacklist specific file types, for example.(jpg|jpeg|gif|css|tif|tiff|png|ttf|woff|woff2|ico) etc etc

~ @m0chan

**Comment by lc** [comment]
Hey @m0chan,

I've considered doing this before, it's a great idea. I'll see if I can implement this

**Comment by lc** [comment]
Hey @m0chan,

I've just released a new version of gau with this implemented - https://github.com/lc/gau/releases/tag/v1.1.0

Thanks!
