### ISSUE TITLE
Not all urls on Waybackmachine are grabbed

### ISSUE THREAD

**Issue by trieulieuf9** [lc/gau#30]
Hi,

First, thank for the great tools, it helps me found several bugs, including my seconds first bug too :)

I notices that a url that i can find on WaybackMachine, but cannot find it in gau output (i tried waybackurls, not found too). The sample url is from a H1 private program, i will send you an email with the sample url instead.

**Comment by lc** [comment]
Hi, glad you've found it useful! Can you email a sample URL to corben[at]threat.dev? Thanks!

**Comment by lc** [comment]
Hey @trieulieuf9,

Can you send me another sample URL again? Thanks.

**Comment by trieulieuf9** [comment]
Hi, @lc 

I just pull urls with gau again, this time the previously missing url is presented in gau result.

**Comment by lc** [comment]
Perfect!
