### ISSUE TITLE
gau not work 

### ISSUE THREAD

**Issue by rami1785** [lc/gau#32]
gau not work as u see in the pic 
i even tried with sudo or by root account 

![gau](https://user-images.githubusercontent.com/77687890/105185357-18119100-5b39-11eb-91c5-c1a134d8baf1.png)

**Comment by bsysop** [comment]
Run `which gau`, you will see it is not properly installed.

Just run
```
./gau -h
```

**Comment by rami1785** [comment]
thank you :)

**Comment by lc** [comment]
`mv gau /usr/local/bin/`
