### ISSUE TITLE
Blacklist is not case sensitive

### ISSUE THREAD

**Issue by NagliNagli** [lc/gau#39]
-b jpg wont catch JPG endpoint

**Comment by lc** [comment]
Hey @NagliNagli,

Good catch, thanks for pointing this out!

**Comment by lc** [comment]
Hi @NagliNagli,

After further investigation, this was fixed about 3 months ago: https://github.com/lc/gau/commit/241494256653f10cb2abd6450db6e0dfa6824b44


 Check to see if your version of gau is up-to-date. Thanks!

**Comment by naglienso** [comment]
Blacklist doesn't work with the version supplied when installing GO111MODULE=on go get -u -v github.com/lc/gau
