### ISSUE TITLE
failed to fetch 

### ISSUE THREAD

**Issue by hcraker350** [lc/gau#41]
failed to fetch wayback pagination: Get "https://web.archive.org/cdx/search/cdx?url=*.example.com/*&output=json&collapse=urlkey&fl=original&page=0&showNumPages=true": dial tcp: i/o timeout
failed to fetch otx results page 0: Get "https://otx.alienvault.com/api/v1/indicators/domain/example.com/url_list?limit=200&page=0": dial tcp: i/o timeout

**Comment by lc** [comment]
This isn't an issue with gau, might be an issue with your DNS

**Comment by h-shawon** [comment]
failed to fetch wayback pagination: json: cannot unmarshal array into Go value of type providers.WaybackPaginationResult
