### ISSUE TITLE
error

### ISSUE THREAD

**Issue by midjarmaksor** [lc/gau#49]
runtime: g1: frame.sp=0xc0001dd5c0 top=0xc0001ddfe0
        stack=[0xc0001dc000-0xc0001de000] n=7 max=2147483647
fatal error: traceback did not unwind completely

runtime stack:
runtime.throw(0x858e48, 0x23)
        /usr/lib/go/src/runtime/panic.go:1116 +0x72
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000180, 0x0, 0x0, 0x7fffffff, 0x867c90, 0x7fff0dc14ef8, 0x0, ...)
        /usr/lib/go/src/runtime/traceback.go:559 +0x1a8a
runtime.copystack(0xc000000180, 0x2000)
        /usr/lib/go/src/runtime/stack.go:910 +0x287
runtime.newstack()
        /usr/lib/go/src/runtime/stack.go:1076 +0x28d
runtime.morestack()
        /usr/lib/go/src/runtime/asm_amd64.s:449 +0x8f

goroutine 1 [copystack]:
runtime.heapBitsSetType(0xc000011590, 0x8, 0x8, 0x7c27a0)
        /usr/lib/go/src/runtime/mbitmap.go:911 +0xaa5 fp=0xc0001dd3e0 sp=0xc0001dd3d8 pc=0x418c65
runtime.mallocgc(0x8, 0x7c27a0, 0x1, 0x400000900)
        /usr/lib/go/src/runtime/malloc.go:1090 +0x5a5 fp=0xc0001dd480 sp=0xc0001dd3e0 pc=0x40f2e5
runtime.growslice(0x7c27a0, 0x0, 0x0, 0x0, 0x1, 0xc0000721e0, 0x0, 0xb0fec0)
        /usr/lib/go/src/runtime/slice.go:230 +0x1e9 fp=0xc0001dd4e8 sp=0xc0001dd480 pc=0x44dee9
runtime.doaddtimer(0xc00002e000, 0xc0000721e8)
        /usr/lib/go/src/runtime/time.go:280 +0x131 fp=0xc0001dd540 sp=0xc0001dd4e8 pc=0x455f71
runtime.addtimer(0xc0000721e8)
        /usr/lib/go/src/runtime/time.go:260 +0xad fp=0xc0001dd578 sp=0xc0001dd540 pc=0x455ded
time.startTimer(0xc0000721e8)
        /usr/lib/go/src/runtime/time.go:207 +0x2b fp=0xc0001dd590 sp=0xc0001dd578 pc=0x468d6b
time.AfterFunc(0x37e11b553, 0xc000053400, 0xb0f9e0)
        /usr/lib/go/src/time/sleep.go:162 +0x91 fp=0xc0001dd5c0 sp=0xc0001dd590 pc=0x4d7e51
what can i do to slove that

**Comment by lc** [comment]
Please update gau :)
