### ISSUE TITLE
Error instantiating proxy

### ISSUE THREAD

**Issue by ramondunker** [lc/gau#51]
Hi there,

Since the update 2.0.4 I'm seeing a weird fatal error.

```
gau example.com
FATA[0005] error instantiating client: empty response, check your proxy configuration
```

This is my .gau.toml file, located in the home directory:

```
threads = 2
verbose = false
retries = 5
subdomains = false
providers = ["gau","commoncrawl","otx","urlscan"]
blacklist = ["ttf","woff","svg","png","jpg"]
json = false

[urlscan]
  apikey = "redacted"

[filters]
  from = ""
  to = ""
  matchstatuscodes = []
  matchmimetypes = []
  filterstatuscodes = []
  filtermimetypes = ["image/png", "image/jpg", "image/svg+xml"]
```

I'm not using any proxy. Am I doing something wrong here?

**Comment by lc** [comment]
Hey @ramondunker,

I’ll look into this tonight, thanks. This occurs when the http client gets an empty response, but from the top of my head, I don’t remember this being a fatal error. Going to look into this as soon as I’m back at my computer.

**Comment by lc** [comment]
Hey @ramondunker,

It seems like this is happening due to CommonCrawl's API being flaky. 

This error "empty response, check your proxy configuration" occurs when the HTTP client gets an empty response (which happens when it can't reach the destination):

> https://github.com/lc/gau/blob/master/pkg/httpclient/client.go#L55

and `error instantiating client` is thrown [here](https://github.com/lc/gau/blob/master/runner/runner.go#L43) when CommonCrawl 503's or can't be reached. I'll add retries to the common crawl instantiation and see if this fixes your problem.

**Comment by lc** [comment]
https://github.com/lc/gau/releases/tag/v2.0.5

**Comment by sumgr0** [comment]
Started getting this after updating to 2.04 and even after 2.05.
gau example.com
FATA[0000] error instantiating client: API responded with non-200 status code

![Screenshot 2021-11-15 at 8 13 02 AM](https://user-images.githubusercontent.com/11391119/141713998-3fe3035c-096e-46b7-8098-2b57f93f5556.JPG)

Are both the errors related, else I shall open a new issue.

**Comment by ramondunker** [comment]
Hi @lc ,

Thanks for the quick response and fix <3

**Comment by ramondunker** [comment]
Hi @lc ,

I just tried version 2.06, but its still not working for me. The error is a little different though:

```
gau example.com --verbose                                                         ✔  8527  14:11:07
WARN[0005] error instantiating commoncrawl: commoncrawl.apiResult: decode slice: expect [ or n, but found , error found in #0 byte of ...||..., bigger context ...||...
```

**Comment by lc** [comment]
I cannot control that commoncrawl is struggling and not responding, so bump up your retries. Gau will still continue to work and this error isn’t fatal, but rather a warning.
