### ISSUE TITLE
error instantiating client: API responded with non-200 status code

### ISSUE THREAD

**Issue by sumgr0** [lc/gau#53]
Started getting this after updating to 2.04 and even after 2.05.
gau example.com
FATA[0000] error instantiating client: API responded with non-200 status code
![Screenshot 2021-11-15 at 8 13 02 AM](https://user-images.githubusercontent.com/11391119/141714423-20df9855-db20-4b34-8b67-3fbde7bde411.JPG)

**Comment by lc** [comment]
Hey @sumgr0, it seems like CommonCrawl is having issues and it responds with 503 every so often, so I am going to just change this from a fatal warning to just a logged issue. I'll fix this quick and you can update. Until then you can use the `-providers wayback,otx,urlscan`

**Comment by lc** [comment]
Also @sumgr0, I'm upping the retry count in the `$HOME/.gau.toml` should help mitigate this as well.

**Comment by sumgr0** [comment]
Using the --providers tag helps. Updated the .gau.toml and its working now.

**Comment by lc** [comment]
Glad to hear it @sumgr0. I'm just about to push a fix so that even if CommonCrawl spazzes gau won't quit and just will continue with the other providers.

**Comment by sumgr0** [comment]
Great... thank you for fixing it this quick :)

**Comment by lc** [comment]
Yep! https://github.com/lc/gau/releases/tag/v2.0.6

**Comment by sudouday** [comment]
same issue again bro (WARN[0001] error instantiating commoncrawl: API responded with non-200 status code)

**Comment by sudouday** [comment]
and this one is working for me now cat httpx.txt | gau --providers wayback,otx,urlscan | tee -a gau.txt

**Comment by lc** [comment]
@sudouday: https://github.com/lc/gau/issues/58
