### ISSUE TITLE
error when installing go

### ISSUE THREAD

**Issue by CR4ZYHUNT** [lc/gau#56]
when i try to install it with go build i got this error 

# command-line-arguments
/usr/bin/ld: /root/.cache/go-build/45/45e7b436531a3ff0bbfde65724b3c47cf223bf26529f52a761b9d83143178b3c-d(_go_.o): in function `github_0com_1modern_x2dgo_1reflect2.UnsafeSliceType.UnsafeMakeSlice':
/root/go/pkg/mod/github.com/modern-go/reflect2@v1.0.2/unsafe_slice.go:78: undefined reference to `reflect.unsafe_NewArray'
/usr/bin/ld: /root/.cache/go-build/45/45e7b436531a3ff0bbfde65724b3c47cf223bf26529f52a761b9d83143178b3c-d(_go_.o): in function `github_0com_1modern_x2dgo_1reflect2.unsafeType.UnsafeNew':
/root/go/pkg/mod/github.com/modern-go/reflect2@v1.0.2/unsafe_type.go:48: undefined reference to `reflect.unsafe_New'
/usr/bin/ld: /root/go/pkg/mod/github.com/modern-go/reflect2@v1.0.2/unsafe_type.go:48: undefined reference to `reflect.unsafe_New'
/usr/bin/ld: /root/go/pkg/mod/github.com/modern-go/reflect2@v1.0.2/unsafe_type.go:48: undefined reference to `reflect.unsafe_New'
/usr/bin/ld: /root/go/pkg/mod/github.com/modern-go/reflect2@v1.0.2/unsafe_type.go:48: undefined reference to `reflect.unsafe_New'
/usr/bin/ld: /root/go/pkg/mod/github.com/modern-go/reflect2@v1.0.2/unsafe_type.go:48: undefined reference to `reflect.unsafe_New'
/usr/bin/ld: /root/.cache/go-build/45/45e7b436531a3ff0bbfde65724b3c47cf223bf26529f52a761b9d83143178b3c-d(_go_.o):/root/go/pkg/mod/github.com/modern-go/reflect2@v1.0.2/unsafe_type.go:48: more undefined references to `reflect.unsafe_New' follow
collect2: error: ld returned 1 exit status

**Comment by lc** [comment]
`go install github.com/lc/gau/v2/cmd/gau@latest` works fine for me. Check your go version and see if you're up to date
