### ISSUE TITLE
403 forbidden error in downloading   https://proxy.golang.org/github.com/klauspost/compress/@v1.31.0

### ISSUE THREAD

**Issue by MR-SS** [lc/gau#57]
hi
when i try to install this tools . i'll get 403 error 

root@localhost:/home/Download# go install github.com/lc/gau/v2/cmd/gau@latest
go: downloading github.com/klauspost/compress v1.13.4
/root/go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/compress.go:10:2: github.com/klauspost/compress@v1.13.4: reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.13.4.zip: 403 Forbidden
/root/go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/compress.go:11:2: github.com/klauspost/compress@v1.13.4: reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.13.4.zip: 403 Forbidden
/root/go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/compress.go:12:2: github.com/klauspost/compress@v1.13.4: reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.13.4.zip: 403 Forbidden

itry it with 2 different ip address but i still getting this error

how can i fix it??

**Comment by lc** [comment]
This works fine for me, maybe try another IP
