### ISSUE TITLE
Gau Not Working 

### ISSUE THREAD

**Issue by tahamarzak20** [lc/gau#60]
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/lc/gau/providers.NewCommonProvider(0xc0000c2300, 0x0, 0x0, 0x0, 0x0)
        /home/dexos/go/pkg/mod/github.com/lc/gau@v1.2.0/providers/common.go:45 +0x2ac
main.run(0xc0000c2300, 0xc000286000, 0x1740, 0x1800)
        /home/dexos/go/pkg/mod/github.com/lc/gau@v1.2.0/main.go:35 +0x98f
main.main()
        /home/dexos/go/pkg/mod/github.com/lc/gau@v1.2.0/main.go:166 +0x7e5

**Comment by knowthetech** [comment]
+1

**Comment by 777388** [comment]
same

**Comment by Brucedh** [comment]
same for me

**Comment by AmbitiousSam** [comment]
+1

**Comment by MohanadIsrewy** [comment]
+1

**Comment by tarunkant** [comment]
Interim solution:
https://github.com/lc/gau/issues/59#issuecomment-1014639657

**Comment by lc** [comment]
Fixed: https://github.com/lc/gau/releases/tag/v2.0.8
