### ISSUE TITLE
not fixed yet panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by GDATTACKER-RESEARCHER** [lc/gau#63]
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/lc/gau/providers.NewCommonProvider(0xc00008e360, 0x0, 0x0, 0x0, 0x0)
/root/go/pkg/mod/github.com/lc/gau@v1.2.0/providers/common.go:45 +0x2ac
main.run(0xc00008e360, 0xc000206000, 0x369, 0x400)
/root/go/pkg/mod/github.com/lc/gau@v1.2.0/main.go:35 +0x98f
main.main()
/root/go/pkg/mod/github.com/lc/gau@v1.2.0/main.go:166 +0x7e5

**Comment by tarunkant** [comment]
I am also receiving the same error.
Install gau using, `go install github.com/lc/gau/v2/cmd/gau@latest`

**Comment by lc** [comment]
https://github.com/lc/gau/releases/tag/v2.0.8

**Comment by knowthetech** [comment]
that seems to be fixed now bro http://index.commoncrawl.org/collinfo.json is having some issue earlier now seems to be fixed

**Comment by lc** [comment]
Yeah, CommonCrawl was having issues: https://groups.google.com/g/common-crawl/c/kEHzXZNu5To

However, gau should no longer panic in the future if this endpoint has errors
