### ISSUE TITLE
WARN[0018] error instantiating commoncrawl

### ISSUE THREAD

**Issue by LucyAKA13** [lc/gau#67]
Every time I try to run cat http-300terra.txt | ./gau 
It gives me this error.
WARN[0018] error instantiating commoncrawl: commoncrawl.apiResult: decode slice: expect [ or n, but found , error found in #0 byte of ...||..., bigger context ...||...

**Comment by MohammadRezaArani** [comment]
Same Happen for me from yesterday!==>
time="2022-02-17T11:53:49+03:30" level=warning msg="error instantiating commoncrawl: commoncrawl.apiResult: decode slice: expect [ or n, but found \x00, error found in #0 byte of ...||..., bigger context ...||...\n"

No matter which domain I ask fro I get the this output when runing:
gau example.com --subs

**Comment by Abdennour-1** [comment]
There will be an update , Check this:

https://commoncrawl.org/2022/03/introducing-cloudfront-access-to-common-crawl-data/

**Comment by Abdennour-1** [comment]
![image](https://user-images.githubusercontent.com/69427610/160026495-258f1f22-30bb-441b-b5cc-c9601ac83c3b.png)
