### ISSUE TITLE
Error Installation

### ISSUE THREAD

**Issue by adrhmnhkm** [lc/gau#7]
I had an error like this .

![Screenshot from 2020-04-28 08-48-54](https://user-images.githubusercontent.com/12286739/80456098-4a38ee00-892d-11ea-8573-55f2e21f42a7.png)

**Comment by adrhmnhkm** [comment]
After updating Go i had new problem like this .

![Screenshot from 2020-04-28 09-11-01](https://user-images.githubusercontent.com/12286739/80457901-52465d00-8930-11ea-9b21-55abd6bafcee.png)

**Comment by lc** [comment]
Hi @adrhmnhkm,

Sorry, it's not your Go version – I had forgotten to update the installation (from source) instructions:

```
▻ go get -u github.com/lc/gau
```
or

```
▻ git clone https://github.com/lc/gau && cd gau
▻ go build -o $GOPATH/bin/gau main.go
```

**Comment by adrhmnhkm** [comment]
Same thing .

> Fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by lc** [comment]
@OGoodness, @adrhmnhkm,

Can you share the command you're running to install?

**Comment by OGoodness** [comment]
@lc 
To install I ran the provided command:

> go get -u github.com/lc/gau

I also tried deleting the bin from the go directory and then building it with:

> ▻ git clone https://github.com/lc/gau && cd gau
> ▻ go build -o $GOPATH/bin/gau main.go

However, I kept getting the errors from above. As a temporary fix, I just built the binary in the repository directory itself, and then added an alias to that directory.

> go build -o ./gau main.go
> alias gau="~/BugHunting/repos/gau/gau"

So, it's working with the alias, it's not that much of a hassle :D

**Comment by lc** [comment]
Hmm... @OGoodness
 
I updated the installation instructions, could you try this? You shouldn't have to do that

```
▻ GO111MODULE=on go get -u -v github.com/lc/gau
```

**Comment by OGoodness** [comment]
@lc  
It works fine now, thank you!
Sorry to bother you with such a simple thing. 

Idk if you say, but NahamSec reviewed your tool on his stream the other day, the VOD is still on Twitch. I think he had some feedback on it.
Keep up the good work, we really enjoy your tools!

**Comment by lc** [comment]
Awesome @OGoodness!

Thanks for verifying that / flagging it, I needed to update the installation instructions after the latest re-factor. Thank you!

**Comment by edoardottt** [comment]
Sorry, but I still have this problem.

**System**:
```
 edoardottt@edoardottt ~/test uname -a
Linux edoardottt 5.8.0-50-generic #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Installation**:
Tried with:
- `GO111MODULE=on go get -u -v github.com/lc/gau`
-  and with the binary `gau_1.1.0_linux_amd64.tar.gz`.

**Go version**: `go version go1.14.7 linux/amd64`

**Error**:
``` 
edoardottt@edoardottt ~/test echo "domain" | gau
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by nuts7** [comment]
Same error.

```
❯ uname -a
Linux c 5.16.10-arch1-1 #1 SMP PREEMPT Wed, 16 Feb 2022 19:35:18 +0000 x86_64 GNU/Linux
❯ go version
go version go1.17.7 linux/amd64
```

**Comment by edoardottt** [comment]
A workaround can be this: if you're using bash as a shell insert in `~/.bashrc`:
```
alias gau=`which gau`
```
if you're using zsh instead `~/.zsh`
