### ISSUE TITLE
WARN[0000] error instantiating commoncrawl.apiResult: decide slice: expect 

### ISSUE THREAD

**Issue by elias1565** [lc/gau#75]
![20220416_210641-2](https://user-images.githubusercontent.com/103888143/163716433-1d590c9a-ae0d-426b-a50d-cb883e7eb0da.jpg)

#67

**Comment by DonatoReis** [comment]
I'm having the same problem when running gau @elias1565 @lc 

### WARN[0000] error instantiating commoncrawl: commoncrawl.apiResult: decode slice: expect [ or n, but found , error found in #0 byte of ...||..., bigger context ...||...

**Comment by ko2sec** [comment]
same with the latest version, 1.1.0 is working properly without any issues.

**Comment by elias1565** [comment]
what command to install the one you reported?

**Comment by elias1565** [comment]
> mesmo com a versão mais recente, 1.1.0 está funcionando corretamente sem problemas.

what command to install the one you reported?

**Comment by ko2sec** [comment]
download from here [https://github.com/lc/gau/releases/tag/v1.1.0](https://github.com/lc/gau/releases/tag/v1.1.0)

**Comment by DonatoReis** [comment]
but what about version 2.1.0?

**Comment by ko2sec** [comment]
> but what about version 2.1.0?

I'm having same problem with the 2.1.0 either.

**Comment by melmel27** [comment]
version https://github.com/lc/gau/releases/tag/v2.0.9 still works fine

**Comment by 4auvar** [comment]
I also facing the same issue.

```
WARN[0000] error instantiating commoncrawl: commoncrawl.apiResult: decode slice: expect [ or n, but found , error found in #0 byte of ...||..., bigger context ...||... 
```

I have installed like `go install github.com/lc/gau/v2/cmd/gau@latest` as given in repository.
Version: 2.1.0

**Comment by lc** [comment]
Hey, looking into this right now

**Comment by lc** [comment]
It's working fine for me:

```
$ echo "lojavtvbox.com" | gau --verbose --providers commoncrawl                              
$ INFO[0000] no results for lojavtvbox.com                 provider=commoncrawl
```

**Comment by ko2sec** [comment]
![image](https://user-images.githubusercontent.com/38421562/164296806-d60f9271-1470-4081-bb4b-7b75392b3f31.png)

maybe related to lack of configuration file?

**Comment by lc** [comment]
Ahhhhhhhhh. No I can reproduce it. Thanks @ko2sec

**Comment by lc** [comment]
Also noticed another major bug. So, thank you!

**Comment by lc** [comment]
Fixed the bugs: https://github.com/lc/gau/releases/tag/v2.1.1
