### ISSUE TITLE
urlscan broken

### ISSUE THREAD

**Issue by molitona** [lc/gau#78]
scanning with urlscan is broken

**Comment by lc** [comment]
Can you provide more information about the issue you're facing?

**Comment by lc** [comment]
Nevermind, I'm see what you're saying.

**Comment by molitona** [comment]
> Nevermind, I'm see what you're saying.

Yeah, that's it.

Please, I've send you a message on twitter, can you respond to it ? it's about a write-up of you.

**Comment by lc** [comment]
Fixed in https://github.com/lc/gau/pull/81

**Comment by molitona** [comment]
> Fixed in #81

could you respond ?
