### ISSUE TITLE
--providers urlscan and wayback not available

### ISSUE THREAD

**Issue by houdinicc** [lc/gau#84]
Hello, I am not getting any urls when I use the following two commands, I don't know what's going on

echo test.com | gau --providers wayback > wayback.txt
echo test.com | gau --providers urlscan > urlscan.txt

**Comment by pdelteil** [comment]
@houdinicc 

Try another domain. It tested it using `google.com` and they work just fine.

**Comment by lc** [comment]
Thank you @pdelteil
