### ISSUE TITLE
go install on fedora

### ISSUE THREAD

**Issue by slossy88** [lc/gau#95]
$ go install github.com/lc/gau/v2/cmd/gau@latest

go/pkg/mod/golang.org/x/net@v0.0.0-20210510120150-4163338589ed/http/httpproxy/export_test.go:1:1: expected 'package', found 'EOF'
go/pkg/mod/golang.org/x/net@v0.0.0-20210510120150-4163338589ed/idna/example_test.go:1:1: expected 'package', found 'EOF'
go/pkg/mod/golang.org/x/net@v0.0.0-20210510120150-4163338589ed/proxy/dial.go:1:1: expected 'package', found 'EOF'
go/pkg/mod/golang.org/x/sys@v0.0.0-20210630005230-0f9fa26af87c/unix/affinity_linux.go:1:1: expected 'package', found 'EOF'
go/pkg/mod/golang.org/x/text@v0.3.6/transform/examples_test.go:1:1: expected 'package', found 'EOF'
go/pkg/mod/golang.org/x/text@v0.3.6/unicode/norm/composition.go:1:1: expected 'package', found 'EOF'
go/pkg/mod/gopkg.in/ini.v1@v1.64.0/bench_test.go:1:1: expected 'package', found 'EOF'
go/pkg/mod/gopkg.in/yaml.v2@v2.4.0/apic.go:1:1: expected 'package', found 'EOF'

**Comment by lc** [comment]
Were you able to get this to work? Please check your go version
